name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: npm install
        run: |
          npm install

      - name: npm build
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Railway
        run: npm i -g @railway/cli
      - run: railway up --service=prolific-wonder
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}